# Generated by Django 3.2.9 on 2022-06-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تخصص')),
            ],
        ),
        migrations.AddField(
            model_name='specialist',
            name='speciality',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Speciality'),
        ),
    ]
