# Generated by Django 3.2.9 on 2022-06-20 03:12

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220604_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, unique=True, verbose_name='شماره تلفن همراه'),
        ),
    ]
