version: "3.9"

volumes:
  postgres_data: {}
  postgres_data_backups: {}

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - core


networks:
  core:
    name: core
    driver: bridge