# Generated by Django 3.2.9 on 2022-06-04 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20220604_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PEND', 'pending'), ('WAIT', 'Waiting for acceptance of the specialist from customer'), ('PROG', 'In Progress'), ('DONE', 'done'), ('CNCL', 'Canceled'), ('REJC', 'Rejected')], default='PEND', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer')),
                ('requested_speciality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.speciality')),
                ('specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.specialist')),
            ],
        ),
    ]
